"""config_emitter — compile ONE governance source into every agent's native rules file.

Pillar 1 (agent-neutral portability): the same policy + packs + method renders into
CLAUDE.md / AGENTS.md, .cursor/rules, .github/copilot-instructions.md, and .clinerules.
Pure string + file generation. Stdlib only, no network.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class GovernanceBundle:
    """The single source of truth that gets emitted to every agent."""
    project: str = "this project"
    method: str = "PromptWise governed agile method"
    policy_summary: list[str] = field(default_factory=list)   # human-readable policy lines
    packs: list[str] = field(default_factory=list)            # active skill packs
    rules: list[str] = field(default_factory=list)            # extra house rules

    def _body(self) -> str:
        out: list[str] = []
        out.append(f"Method: {self.method}.")
        if self.policy_summary:
            out.append("\nGovernance policy (enforced via PromptWise):")
            out += [f"- {p}" for p in self.policy_summary]
        if self.packs:
            out.append("\nActive expert packs:")
            out += [f"- {p}" for p in self.packs]
        if self.rules:
            out.append("\nHouse rules:")
            out += [f"- {r}" for r in self.rules]
        return "\n".join(out)


# (filename, format-label). Each emitter returns file content.
TARGETS = {
    "claude": "CLAUDE.md",
    "agents": "AGENTS.md",
    "cursor": ".cursor/rules/promptwise.mdc",
    "copilot": ".github/copilot-instructions.md",
    "cline": ".clinerules",
}


class ConfigEmitter:
    def emit_claude(self, b: GovernanceBundle) -> str:
        return f"# {b.project} — agent guidance (generated by PromptWise)\n\n{b._body()}\n"

    def emit_agents(self, b: GovernanceBundle) -> str:
        return f"# AGENTS.md — {b.project} (generated by PromptWise)\n\n{b._body()}\n"

    def emit_cursor(self, b: GovernanceBundle) -> str:
        # Cursor .mdc rules use a small frontmatter block.
        return (
            "---\n"
            "description: PromptWise governance + method\n"
            "alwaysApply: true\n"
            "---\n\n"
            f"# {b.project} — PromptWise governance\n\n{b._body()}\n"
        )

    def emit_copilot(self, b: GovernanceBundle) -> str:
        return f"# Copilot instructions — {b.project} (generated by PromptWise)\n\n{b._body()}\n"

    def emit_cline(self, b: GovernanceBundle) -> str:
        return f"# .clinerules — {b.project} (generated by PromptWise)\n\n{b._body()}\n"

    def render(self, bundle: GovernanceBundle, target: str) -> str:
        fn = getattr(self, f"emit_{target}", None)
        if fn is None:
            raise ValueError(f"unknown target '{target}' (known: {list(TARGETS)})")
        return fn(bundle)

    def sync(
        self,
        bundle: GovernanceBundle,
        repo_root: str | Path,
        targets: list[str] | None = None,
        write: bool = True,
    ) -> dict[str, str]:
        """Render (and optionally write) the bundle to each target's native file.

        Returns {relative_path: "written" | "preview"}. Safe: only writes the
        generated files listed in TARGETS, never touches anything else.
        """
        root = Path(repo_root)
        chosen = targets or list(TARGETS)
        result: dict[str, str] = {}
        for t in chosen:
            rel = TARGETS[t]
            content = self.render(bundle, t)
            if write:
                dest = root / rel
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(content, encoding="utf-8")
                result[rel] = "written"
            else:
                result[rel] = content
        return result
