"""web_bundle — single-file, self-contained agent bundle for web-chat hosts.

BMAD-derived idea (docs/GAP_ANALYSIS_2026-07.md §7): ChatGPT / Gemini /
Claude.ai web chat has no IDE, no CLI, no MCP host — there is no native
config file to merge into and no tool-calling surface to wire to. That is
why this is a deliberately SEPARATE code path from config_emitter.py's
managed-block IDE-emitter pattern rather than another TARGETS entry:

  * no merge_managed / managed-block markers — there is no user-owned
    region to preserve, the whole file IS the bundle, and every render
    fully replaces the previous one;
  * not reachable through sync_agent_config's host list — it is exposed as
    its own MCP tool (export_web_bundle).

Pack lookup reuses SkillLoader (name -> Skill.system_prompt) instead of
re-parsing SKILL.md frontmatter itself — composition over reinvention, the
same convention Phase 12's rank_context established. A pack that cannot be
found degrades to a placeholder line; it never fails the whole bundle.

Stdlib only, no network, no persistence beyond an explicit single-file
write the caller opts into via .write().
"""
from __future__ import annotations

from pathlib import Path

from promptwise.core.config_emitter import GovernanceBundle

INTRO = (
    "This is a self-contained governed-agent bundle generated by PromptWise. "
    "Paste this entire file as your first message (or system prompt, if the "
    "host supports one) in ChatGPT, Gemini, or Claude.ai web chat. No IDE, "
    "CLI, or MCP connection is required — everything the agent needs to "
    "follow this project's governance is below."
)

OUTRO = (
    "End of bundle. Follow the governance policy and house rules above for "
    "every response in this conversation."
)


class WebBundleEmitter:
    """Flattens a GovernanceBundle + selected skill packs into one pasteable file."""

    def _pack_body(self, pack_name: str, skill_root: str | Path) -> str | None:
        """Best-effort lookup of a pack's system prompt via SkillLoader.

        Returns None (never raises) when skill_root is missing, the pack is
        unknown, or the pack file fails to parse — the render stays fail-soft.
        """
        try:
            from promptwise.core.skill_loader import SkillLoader
            loader = SkillLoader(Path(skill_root))
            loader.load_skills()
            skill = loader.get_skill(pack_name)
            return skill.system_prompt if skill else None
        except Exception:
            return None

    def render(
        self,
        bundle: GovernanceBundle,
        *,
        skill_root: str | Path = "skill_packs",
        include_packs: bool = True,
    ) -> str:
        """Return the single-file bundle as one string."""
        out: list[str] = [f"# {bundle.project} — PromptWise governed agent (web bundle)", ""]
        out.append(INTRO)
        out.append("")
        out.append(f"Method: {bundle.method}.")
        if bundle.policy_summary:
            out.append("\n## Governance policy")
            out += [f"- {p}" for p in bundle.policy_summary]
        if bundle.rules:
            out.append("\n## House rules")
            out += [f"- {r}" for r in bundle.rules]
        if include_packs and bundle.packs:
            out.append("\n## Active expert packs")
            for pack in bundle.packs:
                body = self._pack_body(pack, skill_root)
                out.append(f"\n### {pack}")
                out.append(body if body else f"(pack '{pack}' content unavailable — reference only)")
        out.append("\n---")
        out.append(OUTRO)
        return "\n".join(out) + "\n"

    def write(
        self,
        bundle: GovernanceBundle,
        out_path: str | Path,
        *,
        skill_root: str | Path = "skill_packs",
        include_packs: bool = True,
    ) -> str:
        """Render and write ONE standalone file (full overwrite, no merge —
        there is no managed-block protocol for this distribution mode).
        """
        content = self.render(bundle, skill_root=skill_root, include_packs=include_packs)
        dest = Path(out_path)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        return content
